name: RCPM Hourly (multi-pair)

on:
  schedule:
    - cron: "7 * * * *"    # every hour at :07 UTC
  workflow_dispatch:       # allow manual runs

concurrency:
  group: rcpm-hourly
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run updater
        env:
          TEQBLAZE_EMAIL: ${{ secrets.TEQBLAZE_EMAIL }}
          TEQBLAZE_PASSWORD: ${{ secrets.TEQBLAZE_PASSWORD }}
          # Provide one or more bases (comma, semicolon, or newline separated)
          BASE_FILTERS: ${{ 33across_001Pg0000197KcKIAU_IA_display_USeast,Media.net_IA_8CU43768M_Video_Prebid_USeast }}
          # Optional tuning:
          LIVE_UPDATES: "true"
          TIME_ZONE: "UTC"
          PAGE_LIMIT: "50000"
        run: |
          python scripts/rcpm_hourly_multipair.py

      - name: Upload artifacts (CSVs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rcpm-csvs-${{ github.run_id }}
          path: |
            report output/**/*
          if-no-files-found: warn
